Refactoring the logic and structure
dan9Protasenia/Multiprocessing_task pull request #2
Opened 2023-12-09 21:10 UTC by dan9Protasenia

- Transfers the logic of metric processing to a separate worker_manager module.
- Improves the readability and structure of the code.
- Uses multiples of 10 and limits the range to hundreds for metrics.
- Updates logging.

2023-12-10 16:17 UTC, RoTorEx requested changes
И не забудь в Readme.md описать как работает твоя программа в этой же ветке.
Кстати о ветках, забыл дать ещё пояснений. В будущем используй - вмеcто /, потому что на некоторых операционках, особенно на Винде, будет ломаться git

2023-12-10 16:17 UTC, RoTorEx commented on client/worker.py
> +from Multiprocessing_task.constant import LOCAL_HOST
<img width="1145" alt="image" src="https://github.com/dan9Protasenia/Multiprocessing_task/assets/78344396/5a3b964d-1ce6-4187-9735-b5a9dc1bcb59">

2023-12-10 16:17 UTC, RoTorEx commented on client/main.py
> +from Multiprocessing_task.constant import LOCAL_HOST
Тоже самое ниже

2023-12-10 16:17 UTC, RoTorEx commented on constant.py
> +METRICS_FILE = "metrics.json"
У тебя нет в конце файла пустой строки, что может ломать файл и кодировку строк

2023-12-10 16:17 UTC, RoTorEx commented on server/master.py
> +from Multiprocessing_task.constant import LOCAL_HOST, METRICS_FILE
Тоже самое

2023-12-10 16:17 UTC, RoTorEx commented on server/master.py
> +            if current_time - start_time_10s >= 10:
Слипается код

2023-12-10 16:17 UTC, RoTorEx commented on server/main.py
> +    master(master_port)
Нам нужно иметь один исполняемый файл, который запустить мастер и воркер процесс. Оставь один воркер процесс, если кажется сложным

2023-12-10 16:17 UTC, RoTorEx commented on server/main.py
> +    master(master_port)
Фактически это всё может быть аккуратно упаковано в одном модуле с использованием классов для воркеров с определением константных атрибутов, например. И логгер и запись в файл в другом модуле, как утилиты. Хотя даже логгер здесь не нужен, у нас фактически весь отпут программы и там должен быть виден в джосоне

2023-12-10 16:17 UTC, RoTorEx commented on client/worker.py
> +from Multiprocessing_task.constant import LOCAL_HOST
Неправильные импорты, вне корня проекта

2023-12-11 11:00 UTC, RoTorEx requested changes
Хорошо, поправь замечания и допиши тут же документацию в `README.md`, можешь со скринами. Познакомься с `.md` форматом.

2023-12-11 11:00 UTC, RoTorEx commented on worker.py
> +        logging.info(f"Master started. Port {MASTER_PORT}")
Код слипается и его можно разделить на логические части

2023-12-11 11:00 UTC, RoTorEx commented on worker.py
> +        write_metrics_to_file(self.output_file, metric_data)
Если ты импортишь внешние файлы они не должны иметь такое же название, во первых это не читаемо, в том числе для идешки, во вторых тебе не надо расширять класс ненужными методами, если та мнет никакой логики, напрямую вызывай заимпорченные методы, где тебе нужно

2023-12-11 11:00 UTC, RoTorEx commented on worker.py
> +            self.sock.close()
Тут тоже слипается код, как минимум 2 пробела нужно

2023-12-11 11:00 UTC, RoTorEx commented on worker.py
> +            sys.exit(0)
Тоже самое со слипанием

2023-12-11 11:00 UTC, RoTorEx commented on tools.py
> +    write_metrics_to_file(metric_data)
Не могу понять зачем ты пишешь в файл с логов + из методов класса?

2023-12-11 11:00 UTC, RoTorEx commented on logger.py
>      )
Фактически логгер ты можешь вынести так же тулс

2023-12-11 11:00 UTC, RoTorEx commented on worker.py
> +    master.start()
Логично файл тоже назвать `main.py`, если он у тебя энтрипоинт

2023-12-11 11:04 UTC, RoTorEx commented
Так же есть под комментами кнопочка `Resolve conversation`, закрывай диалоги ненужные

2023-12-12 13:10 UTC, dan9Protasenia commented on constant.py
> +METRICS_FILE = "metrics.json"
![image](https://github.com/dan9Protasenia/Multiprocessing_task/assets/100715839/e318ef55-adb5-44d6-8608-a78c39908668)

2023-12-12 16:46 UTC, dan9Protasenia commented on worker.py
> +            self.sock.close()
не совсем понял про слипание здесь

2023-12-12 16:47 UTC, dan9Protasenia commented on worker.py
> +            sys.exit(0)
и здесь не понял про слипание

2023-12-12 16:54 UTC, RoTorEx commented on constant.py
> +METRICS_FILE = "metrics.json"
Да, всё чётко, это был старый коммент, сейчас всё окей

2023-12-12 17:25 UTC, RoTorEx commented on constant.py
> +METRICS_FILE = "metrics.json"
А нет, у тебя эта страчка не закомичена, вот алярм
![image](https://github.com/dan9Protasenia/Multiprocessing_task/assets/78344396/049e93d1-b759-4042-a967-b44d0b513514)

2023-12-12 17:25 UTC, RoTorEx commented on worker.py
> +        logging.info(f"Master started. Port {MASTER_PORT}")
Просто добавь пару пробелов, чтобы визуально флоу сокетов отделить, хотя лучше вызов методов не пихать в __init__

2023-12-12 17:25 UTC, RoTorEx commented on worker.py
> +            sys.exit(0)
Цикл for выдели пробелами дополнительными, чтобы он быстрее и лучше читался

2023-12-12 17:25 UTC, RoTorEx commented on worker.py
> +            self.sock.close()
Перед finally добавь пробел и после того, как цикл закончится, потом кайфанёшь от того, что код визуально смотрится логично и чисто

2023-12-12 17:29 UTC, dan9Protasenia commented on worker.py
> +        logging.info(f"Master started. Port {MASTER_PORT}")
а я уже начал логически разделять на блоки отдельные :)
![image](https://github.com/dan9Protasenia/Multiprocessing_task/assets/100715839/0ace45af-ecc0-4e3b-b423-3572a5737fa2)

2023-12-12 17:30 UTC, dan9Protasenia commented on worker.py
> +        logging.info(f"Master started. Port {MASTER_PORT}")
оставить так?
или убрать вызов методов из инит?

2023-12-12 17:31 UTC, RoTorEx commented on worker.py
> +        logging.info(f"Master started. Port {MASTER_PORT}")
Лучше убери, если у тебя будет асинхронный код, то вызов методов в init будет блокировать асинхронный поток, потому что он синхронный

2023-12-12 18:01 UTC, dan9Protasenia commented
получилось два разных main файла, потому что я сначала сделал одним способом потом поменял но не откатил коммит для main 
(не совсем понял как это сделать :( )

2023-12-12 18:58 UTC, RoTorEx commented
> получилось два разных main файла, потому что я сначала сделал одним способом потом поменял но не откатил коммит для main (не совсем понял как это сделать :( )

Что значит не откатил коммит для main?

2023-12-12 19:02 UTC, dan9Protasenia commented
ну я сначала сделал коммит с одной правкой, а потом сам не понял как сделал с другой
но последняя версия вроде как нужная 
![image](https://github.com/dan9Protasenia/Multiprocessing_task/assets/100715839/1b59da54-d44f-499c-a8ca-e47eafd003a1)

2023-12-12 19:57 UTC, RoTorEx approved these changes
Здорово, хорошее решение, приятно смотреть на обработку интеррапта)

2023-12-12 19:57 UTC, RoTorEx commented on main.py
> +        self.sock.bind((LOCAL_HOST, MASTER_PORT))
Вот такие шутки, как я и писал, в конструкторах лучше не держать

2023-12-12 19:57 UTC, RoTorEx commented on main.py
> +        signal.signal(signal.SIGINT, handle_termination)
Лайк!

2023-12-12 19:57 UTC, RoTorEx commented on constant.py
> +
<img width="335" alt="image" src="https://github.com/dan9Protasenia/Multiprocessing_task/assets/78344396/6c552b34-5b97-485c-9bdc-d40651868329">
Гляди, мне идешка подсвечивает лишную строку, это придирки конечно. Но можешь себе в среде настроить авто удаление висящий пробелов, и авто установку символа переноса строки в каждый файл, чтобы кодировку не ломать. Был бы у тебя vsc, я бы тебе зашарил свой конфиг потыкать.

2023-12-12 19:57 UTC, RoTorEx commented on main.py
> +                process.terminate()
Мне кажется, что это недостижимый код, потому что ты сигналом `Interrupt` обрабатываешь и там всё завершаешь, но возможно ты тут хотел что-то другое обработать. Что скажешь?

2023-12-12 19:57 UTC, RoTorEx commented on main.py
> +    def __init__(self, num_workers, output_file="metrics.json"):
Лайк за решение с классами!

2023-12-12 19:57 UTC, RoTorEx commented on README.md
> +This project demonstrates a simple metrics aggregation system using multiprocessing
Лайк за документацию!

2023-12-12 20:00 UTC, RoTorEx commented
А коммиты ты можешь отказывать назад через `git reset @~num` (но тут есть несколько флагов, важно их не путать, чтобы всё не пропало :)). А если ты сделал `git reset @~5 --hard` и всё пропало, то можно вернуть через `git reset @{5}`.

2023-12-12 20:38 UTC, merged

2023-12-12 20:54 UTC, RoTorEx commented on main.py
> +                process.terminate()
@dan9Protasenia, нужен твой комментарий)

2023-12-12 21:02 UTC, dan9Protasenia commented on main.py
> +                process.terminate()
ну здесь я хотел чтоб при ctrl + c у меня завершались все процессы

2023-12-12 21:07 UTC, dan9Protasenia commented on main.py
> +                process.terminate()
для корректного завершения проги 
так скажу, что без него у меня ctrl + c не работает

2023-12-12 21:39 UTC, RoTorEx commented on main.py
> +                process.terminate()
А у тебя появляется эта запись в консоли `Master terminated`?
У меня просто нет, вот я и судя по коду мастер процесс должен закрыть через `handle_termination` не дойдя до этого `try/except`

2023-12-12 21:44 UTC, dan9Protasenia commented on main.py
> +                process.terminate()
ну в целом да 
недостижимый кож